# Generated by Django 5.1.1 on 2024-09-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hometask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('ENG', 'Английский язык'), ('RUS', 'Русский язык'), ('ALG', 'Алгебра'), ('GEO', 'Геометрия'), ('GRH', 'География'), ('PEC', 'Физкультура'), ('HIM', 'Химия'), ('OBZ', 'ОБЖ'), ('BIO', 'Биология'), ('PHS', 'Физика'), ('INF', 'Информатика'), ('LIT', 'Литература'), ('IST', 'История'), ('TRD', 'Труды')], max_length=3, verbose_name='Предмет')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='Дата задания')),
                ('status', models.CharField(choices=[('RES', 'Решено'), ('NOT', 'Нерешено'), ('URG', 'СРОЧНО')], default='NOT', max_length=3, verbose_name='Статус')),
                ('task_text', models.TextField(verbose_name='Текст задания')),
                ('due_date', models.DateField(verbose_name='Срок выполнения')),
            ],
        ),
    ]
