# Generated by Django 5.1.1 on 2024-09-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HWH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometask',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок сдачи'),
        ),
    ]
