# Generated by Django 5.1.1 on 2024-09-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HWH', '0002_hometask_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometask',
            name='status',
            field=models.CharField(blank=True, choices=[('RES', 'Решено'), ('NOT', 'Нерешено'), ('URG', 'СРОЧНО')], default='NOT', max_length=3, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='hometask',
            name='task_text',
            field=models.TextField(max_length=256, verbose_name='Текст задания'),
        ),
    ]
